### GET request with a header
GET http://localhost:8000/events
### POST request with a header
POST http://localhost:8000/events
Content-Type: application/json

{
  "workspaceId": "workspaceId",
  "userId": "userId",
  "mem": 100,
  "cpu": 80,
  "io": 4
}
